// Category types
export const SET_LOADING_CATEGORY = 'SET_LOADING_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_IN_PROCESS = 'SET_IN_PROCESS';

// Questions types
export const SET_LOADING_QUESTIONS = 'SET_LOADING_QUESTIONS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SUBMIT_ANSWER_ON_QUESTION = 'SUBMIT_ANSWER_ON_QUESTION';
