// User
export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_USER = "SET_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER= "UPDATE_USER";
export const UPDATE_CURRENT_USER= "UPDATE_CURRENT_USER";
export const LOGOUT = "LOGOUT";

// Category types
export const SET_LOADING_CATEGORY = 'SET_LOADING_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_IN_PROCESS = 'SET_IN_PROCESS';
export const UPDATE_TIME = 'UPDATE_TIME';

// Questions types
export const SET_LOADING_QUESTIONS = 'SET_LOADING_QUESTIONS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SUBMIT_ANSWER_ON_QUESTION = 'SUBMIT_ANSWER_ON_QUESTION';
export const RESTART_QUIZ = 'RESTART_QUIZ';
