// Category types
export const SET_LOADING_CATEGORY = 'SET_LOADING_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

// Questions types
export const SET_LOADING_QUESTIONS = 'SET_LOADING_QUESTIONS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
